Move image upload section in main() to function upload_image(); Dialog to show screenshot before uploading; Add function 'return_to_desktop()';

diff --git a/imgbb/imgbb b/imgbb/imgbb
--- a/imgbb/imgbb
+++ b/imgbb/imgbb
@@ -342,34 +342,7 @@ function switch_to_active(){   # switch to new browser tab
     done
 }
 
-function main(){
-    settings_conf   # set up imgbb.conf if necessary
-
-    # set defaults
-    SCROT="${SCREENSHOT_FULL_COMMAND}"        
-
-    export -f run_browser   # to be used as YAD button command
-    export -f switch_to_active # switch to active window
-    export -f show_image        # to be used as YAD button command
-    
-    export VIEWER=$(grep -oP '(?<=VIEWER=").*(?=")' "${SETTINGS_FILE}")
-    # for use by show_image()
-    [[ -z "${VIEWER}" ]] && VIEWER="x-www-browser"
-
-    if ! . "${BL_YAD_INCLUDES}" 2> /dev/null; then
-        echo "Error: Failed to source yad-includes in ${BL_YAD_INCLUDES}" >&2
-        exit 1
-    elif ! . "${SETTINGS_FILE}" 2> /dev/null; then
-        echo "Error: Failed to source ${SETTINGS_FILE} in ${USR_CFG_DIR}/" >&2
-        exit 1
-    fi
-    
-    check_required  # check required programs are installed
-    
-    [[ -z "${CLIENT_API_KEY}" ]] && get_client_api_key
-    getargs "${@}"
-    getimage "${FNAME}"
-     
+function upload_image(){
     temp_file=$(mktemp --tmpdir response.XXX) # stores curl output for use by ${response}
     curl_cmd="curl -s --location --request POST https://api.imgbb.com/1/upload?key=${CLIENT_API_KEY} \
     --form image=@${img_file}"
@@ -407,6 +380,69 @@ set +x
         Use Ctrl-C/Ctrl-V to copy/paste the selection
 
         '
+}
+
+function return_to_desktop(){
+    local curr_desktop="$1"
+    if [[ ${VIEWER} = "x-www-browser" ]];then
+        xdotool key ctrl+w  # close current tab
+    else
+        pkill -xf "${VIEWER} ${img_file}"
+    fi
+    xdotool set_desktop ${curr_desktop}
+}
+
+function main(){
+    settings_conf   # set up imgbb.conf if necessary
+
+    # set defaults
+    SCROT="${SCREENSHOT_FULL_COMMAND}"        
+
+    export -f run_browser   # to be used as YAD button command
+    export -f switch_to_active # switch to active window
+    export -f show_image        # to be used as YAD button command
+    
+    export VIEWER=$(grep -oP '(?<=VIEWER=").*(?=")' "${SETTINGS_FILE}")
+    # for use by show_image()
+    [[ -z "${VIEWER}" ]] && VIEWER="x-www-browser"
+
+    if ! . "${BL_YAD_INCLUDES}" 2> /dev/null; then
+        echo "Error: Failed to source yad-includes in ${BL_YAD_INCLUDES}" >&2
+        exit 1
+    elif ! . "${SETTINGS_FILE}" 2> /dev/null; then
+        echo "Error: Failed to source ${SETTINGS_FILE} in ${USR_CFG_DIR}/" >&2
+        exit 1
+    fi
+    
+    check_required  # check required programs are installed
+    
+    [[ -z "${CLIENT_API_KEY}" ]] && get_client_api_key
+    getargs "${@}"
+    getimage "${FNAME}"
+    
+    # Option to show screenshot before uploading 
+    dtop="$(xdotool get_desktop)" 
+    while true;do
+        ${DIALOG} --undecorated --sticky --on-top --image=gtk-dialog-question --center \
+        --button="Show screenshot?:2" \
+        --button="Upload:4" \
+        --button="Exit:1"
+
+        ans=$?
+        case ${ans} in
+            2)  show_image
+                continue
+                ;;
+            4)  upload_image
+                break
+                ;;
+            *)  delete_local
+                exit
+                ;;
+        esac
+    done
+    return_to_desktop "${dtop}"
+
     # Show 'Delete' button until image has been deleted
     while true;do
         if wget --spider "${del_url}" 2>/dev/null; then # page exists
